USE SocialMediaProject;
GO

-- Database Values (Generated by AI)

-- =========================================
-- INSERT USERS
-- =========================================
INSERT INTO users (username, email, uName, [password], dateOfBirth) VALUES
('joaosilva',   'joao.silva@mail.com',    'João S.',    'hash_pw_001', '1995-03-14'),
('mariacosta',  'maria.costa@mail.com',   'Maria C.',   'hash_pw_002', '1998-07-22'),
('pedrolopes',  'pedro.lopes@mail.com',   'Pedro L.',   'hash_pw_003', '1992-11-05'),
('anafernandes','ana.fernandes@mail.com', 'Ana F.',     'hash_pw_004', '2000-01-30'),
('rui_matos',   'rui.matos@mail.com',     'Rui M.',     'hash_pw_005', '1996-09-18'),
('sofiareis',   'sofia.reis@mail.com',    'Sofia R.',   'hash_pw_006', '1999-05-12'),
('tiagogomes',  'tiago.gomes@mail.com',   'Tiago G.',   'hash_pw_007', '1993-12-01'),
('inesalves',   'ines.alves@mail.com',    'Inês A.',    'hash_pw_008', '2001-04-27');
GO

-- =========================================
-- INSERT POSTS (publicações "originais")
-- IDs esperados: 1..10
-- =========================================
INSERT INTO posts (userID, [text]) VALUES
(1, 'Bom dia! Alguém tem sugestões de livros de ficção científica?'),   -- id 1
(2, 'Acabei de terminar o meu primeiro projeto em SQL Server 🎉'),      -- id 2
(3, 'O trânsito hoje em Lisboa está impossível...'),                    -- id 3
(4, 'Recomendam algum café bom para trabalhar remotamente?'),           -- id 4
(5, 'Já viram o novo filme do Villeneuve? Que obra-prima.'),            -- id 5
(6, 'Treino feito ✅ Agora sim, café bem merecido.'),                   -- id 6
(7, 'Alguém consegue explicar-me joins em SQL de forma simples?'),      -- id 7
(8, 'A minha gata partiu-me outra caneca. Terceira esta semana.'),      -- id 8
(1, 'Playlist nova no Spotify, deixem sugestões nos comentários!'),     -- id 9
(3, 'Portugal ganhou! Que jogo incrível 🇵🇹');                          -- id 10
GO

-- =========================================
-- INSERT COMMENTS
-- Cada comentário é PRIMEIRO um post (na tabela posts),
-- e depois é registado em comments a apontar ao post original.
-- =========================================

-- Comentário ao post 1 (livros ficção científica)
INSERT INTO posts (userID, [text]) VALUES (2, 'Recomendo "Duna" do Frank Herbert!');           -- id 11
INSERT INTO comments (id, postCommented) VALUES (11, 1);

INSERT INTO posts (userID, [text]) VALUES (5, 'Vê "Fundação" do Asimov, é brutal.');           -- id 12
INSERT INTO comments (id, postCommented) VALUES (12, 1);

INSERT INTO posts (userID, [text]) VALUES (7, '"Neuromancer" do Gibson, cyberpunk clássico.'); -- id 13
INSERT INTO comments (id, postCommented) VALUES (13, 1);

-- Comentários ao post 2 (projeto SQL)
INSERT INTO posts (userID, [text]) VALUES (3, 'Parabéns! SQL Server é excelente.');            -- id 14
INSERT INTO comments (id, postCommented) VALUES (14, 2);

INSERT INTO posts (userID, [text]) VALUES (8, 'Boa Maria! Partilha o repositório.');           -- id 15
INSERT INTO comments (id, postCommented) VALUES (15, 2);

-- Comentários ao post 3 (trânsito)
INSERT INTO posts (userID, [text]) VALUES (4, 'Confirmo, demorei 1h para 5km 😤');             -- id 16
INSERT INTO comments (id, postCommented) VALUES (16, 3);

INSERT INTO posts (userID, [text]) VALUES (6, 'Metro é sempre a melhor opção.');               -- id 17
INSERT INTO comments (id, postCommented) VALUES (17, 3);

-- Comentários ao post 4 (café para trabalhar)
INSERT INTO posts (userID, [text]) VALUES (1, 'O Fábrica Coffee Roasters em Lisboa é top.');   -- id 18
INSERT INTO comments (id, postCommented) VALUES (18, 4);

INSERT INTO posts (userID, [text]) VALUES (5, 'Copenhagen Coffee Lab, tem bom wifi.');         -- id 19
INSERT INTO comments (id, postCommented) VALUES (19, 4);

-- Comentário ao post 5 (filme Villeneuve)
INSERT INTO posts (userID, [text]) VALUES (2, 'Vi ontem, a fotografia é de outro mundo.');     -- id 20
INSERT INTO comments (id, postCommented) VALUES (20, 5);

-- Comentário ao post 7 (joins SQL)
INSERT INTO posts (userID, [text]) VALUES (2, 'INNER JOIN = interseção; LEFT JOIN = tudo da esquerda + match.'); -- id 21
INSERT INTO comments (id, postCommented) VALUES (21, 7);

INSERT INTO posts (userID, [text]) VALUES (3, 'Vê o site sql-joins do Ligaya, tem diagramas.'); -- id 22
INSERT INTO comments (id, postCommented) VALUES (22, 7);

-- Comentário ao post 8 (gata)
INSERT INTO posts (userID, [text]) VALUES (6, 'Hahaha os gatos são assim mesmo 🐱');            -- id 23
INSERT INTO comments (id, postCommented) VALUES (23, 8);

-- Comentário ao post 10 (Portugal ganhou)
INSERT INTO posts (userID, [text]) VALUES (7, 'Que noite épica! 🇵🇹⚽');                        -- id 24
INSERT INTO comments (id, postCommented) VALUES (24, 10);

INSERT INTO posts (userID, [text]) VALUES (8, 'Ainda estou eufórica!');                        -- id 25
INSERT INTO comments (id, postCommented) VALUES (25, 10);

-- Resposta a comentário (comentário do comentário 11)
INSERT INTO posts (userID, [text]) VALUES (1, 'Já li Duna, adorei! Obrigado pela dica.');      -- id 26
INSERT INTO comments (id, postCommented) VALUES (26, 11);

GO

-- =========================================
-- INSERT LIKES
-- Um utilizador não pode dar like duas vezes ao mesmo post (PK composta).
-- =========================================
INSERT INTO likes (userID, postID) VALUES
-- Post 1
(2, 1), (3, 1), (5, 1), (7, 1), (8, 1),
-- Post 2
(1, 2), (3, 2), (4, 2), (6, 2), (7, 2), (8, 2),
-- Post 3
(1, 3), (4, 3), (6, 3),
-- Post 4
(1, 4), (2, 4), (5, 4), (7, 4),
-- Post 5
(1, 5), (2, 5), (3, 5), (6, 5), (8, 5),
-- Post 6
(1, 6), (4, 6), (8, 6),
-- Post 7
(2, 7), (3, 7), (5, 7),
-- Post 8
(1, 8), (2, 8), (4, 8), (5, 8), (6, 8), (7, 8),
-- Post 9
(2, 9), (4, 9), (6, 9),
-- Post 10 (post popular)
(1, 10), (2, 10), (4, 10), (5, 10), (6, 10), (7, 10), (8, 10),
-- Likes em comentários (também são posts)
(1, 11), (4, 11), (6, 12),
(1, 14), (7, 15),
(2, 21), (4, 21), (5, 21), (6, 21), (7, 21),
(3, 24), (5, 24);
GO

-- =========================================
-- Verificação rápida
-- =========================================
SELECT p.id, u.username, p.[text],
       dbo.likeNumber(p.id)     AS likes,
       dbo.commentsNumber(p.id) AS comentarios
FROM posts p
JOIN users u ON u.id = p.userID
ORDER BY p.id;
GO